### ISSUE TITLE
Fix remaining `clippy` linter issues

### ISSUE THREAD

**Issue by antoniosarosi** [BoundaryML/baml#2071]
PR #2067 fixes most of the `clippy` warnings, but some of them that are not trivial to fix where added as `"allow"` in `Cargo.toml` files just to pass CI. Use <kbd>CTRL</kbd> + <kbd>SHIFT</kbd> + <kbd>F</kbd> or whatever your editor uses for searching multiple files and search for these lines individually:

```toml
module_inception = "allow"
result_large_err = "allow"
large_enum_variant = "allow"
type_complexity = "allow"
too_many_arguments = "allow"
arc_with_non_send_sync = "allow"
```

Remove them one by one from the corresponding `Cargo.toml` files and  run `RUSTFLAGS="-A unused" cargo clippy` on the `engine` directory, fixing the warnings until all the lines above are removed from all the `Cargo.toml` files.
